# Generated by Django 4.2 on 2023-06-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagement', '0003_rename_result_schoolresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='full_name',
        ),
    ]
