# Generated by Django 4.2 on 2023-05-13 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagement', '0001_initial'),
        ('userManagement', '0002_user_school_class_user_school_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolManagement.schoolclass'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolManagement.schoolsession'),
        ),
    ]
