# Generated by Django 4.2 on 2023-05-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matric',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
